### ISSUE TITLE
Get sponsors widget working properly

### ISSUE THREAD

**Issue by brashrebel** [sportstimemachine/theme2016#5]
Right now there are major issues with the sponsors widget that displays in the right sidebar.
- Sponsors are specific to the two sides of the site (start and summit) but right now, it seems that incorrect sponsors are showing on both sides. We need to make sure start sponsors show for start and summit for summit.
- Apparently, some sponsors are not linking to the right place. We need to investigate and fix if we can.
- Sponsor ad order in the widget needs to be `rand` so it changes each page load.

**Comment by d4mation** [comment]
From what I can tell, the Sponsors are all linking to the correct places when they have a Link assigned.

A few of the Sponsors do not have Links assigned: STM – Stark Edition, STM – Summit, and Canton Aluminum (On the Summit Side).

I have made it so that the Link field is a required field which should prevent this from happening in the future.
